### ISSUE TITLE
PHP Fatal error:  Class 'WPCOM_VIP_CLI_Command' not found

### ISSUE THREAD

**Issue by hauvong** [Penske-Media-Corp/pmc-theme-unit-test#14]
Plugin is throwing fatal error when activate as stand alone plugin:

`PHP Fatal error:  Class 'WPCOM_VIP_CLI_Command' not found in /srv/www/wp-content/plugins/pmc-theme-unit-test/wpcli/class-pmc-wp-cli-base.php on line 7`

The CLI class need to rewrite to not depend on any other class from other plugins.

**Comment by hauvong** [comment]
Fatal error: Cannot redeclare class PMC_WP_CLI_Base in /srv/www/wp-content/themes/vip/pmc-p
lugins/pmc-wp-cli/class-pmc-wp-cli-base.php on line 105

**Comment by hauvong** [comment]
Should remove class-pmc-wp-cli-base.php & class-pmc-wp-cli.php, these class are use for common cli functions that this plugin might would not use.  Any function that need, should just be copy over to pmc-theme-unit-test-wp-cli.php;  this would remove all class conflict, etc...

**Comment by amandhare** [comment]
This is fixed.
