### ISSUE TITLE
Better handling of OAuth2 code and redirect url

### ISSUE THREAD

**Issue by mintindeed** [Penske-Media-Corp/pmc-theme-unit-test#2]
* Currently you have to manually copy the `code` from the URL after authenticating, and paste it into a text box, to import content. This should be streamlined.
* Currently you have to have a real domain associated with your application for the OAuth2 redirect URI, but this plugin is meant to be used on dev environment. Dev environments are most commonly on laptops and desktops, with inaccessible TLDs like `.local` and `.dev`. 

This should probably support what WP.com calls a `Web` type application, which I think would solve both those problems.

**Comment by mintindeed** [comment]
I use https://ngrok.com/ for my dev environment which skirts around the issue.

**Comment by hauvong** [comment]
Related to issue #26

**Comment by hauvong** [comment]
This ticket can be close.  WP app allow *.local domain to use and we have a default configuration OAuth app and redirect url set to http://vip.local/redirectme
