### ISSUE TITLE
Ability to run from wp-cli

### ISSUE THREAD

**Issue by mintindeed** [Penske-Media-Corp/pmc-theme-unit-test#4]
Probably related to #2 and maybe #3 - the ability to run imports (and selective imports) from the command line would be useful.

**Comment by amandhare** [comment]
Added support to run the plugin from wp-cli.

**Comment by amandhare** [comment]
* For selected routes
__wp --url=deadline.vip.local pmc-import-live import-routes --routes=users__

* For complete theme data import
__wp --url=deadline.vip.local pmc-import-live import-all__

Please check the file _pmc-theme-unit-test-wp-cli.php_ for more information on the commad parameters
