### ISSUE TITLE
Getting fatal error for PMC_Singleton not found

### ISSUE THREAD

**Issue by asannad** [Penske-Media-Corp/pmc-theme-unit-test#9]
FATAL ERROR: Array
(
    [type] => 1
    [message] => Class 'PMC\Theme_Unit_Test\PMC_Singleton' not found
    [file] => /srv/www/wp-content/themes/vip/pmc-plugins/pmc-theme-unit-test/classes/admin.php
    [line] => 4
)

This might be fixed by removing  if (  class_exists( 'PMC_Singleton' ) )  check in admin.php. Irrespetive of whether PMC_Singleton exists or not it might be fine to just define it in your namespace.

**Comment by coolamit** [comment]
The issue is that `PMC\Theme_Unit_Test\Admin` is defined as

```php
class Admin extends PMC_Singleton {}
```

It should reference `PMC_Singleton` from root namespace, so it should either do:

```php
class Admin extends \PMC_Singleton {}
```

or 

```php
use \PMC_Singleton;

class Admin extends PMC_Singleton {}
```

**Comment by amandhare** [comment]
Could not replicate.
